# Generated by Django 5.1.2 on 2025-02-12 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_customuser_public_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='public_key',
        ),
    ]
