# Generated by Django 5.1.2 on 2025-02-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_customuser_public_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='encryption_key',
            field=models.CharField(blank=True, max_length=44, null=True),
        ),
    ]
